apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nto0sndpe-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nto0sndpe-nodejs 
  name: nto0sndpe-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nto0sndpe-nodejs 
